spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
  jackson:
    property-naming-strategy  : SNAKE_CASE
